### ISSUE TITLE
Warn users of version mismatch

### ISSUE THREAD

**Issue by ajbt200128** [returntocorp/semgrep-vscode#22]
Inform users if their current version of semgrep is incompatible with the current extension version. Allow some sort of updating dialogue

**Comment by bbrks** [comment]
This just bit me trying to run with semgrep 0.104.0 which had incompatible `lsp --config` behaviour.

Once I updated to 0.108.0 everything works great

**Comment by oriolgual** [comment]
After upgrading (tried with 0.108.0 and 0.113.0, currently at 0.107.0) I'm getting this error:

```
2022-09-19 09:29:47,692 - semgrep.lsp.server - ERROR - Scan failed: 
invalid configuration file found (1 configs were invalid)
Scan failed: 
invalid configuration file found (1 configs were invalid)
```

But running `semgrep scan --validate=/path/to/config` says everything is OK

Did you find a way to fix?

The only thing I've found is to keep 0.107.0 and add `cmdlineOpts.push(...["--config=/path/to/configl"]);` to the extension code, but this does not work on 0.107+ versions since there's no `config` option.

**Comment by ajbt200128** [comment]
We warn users of version mismatch in v1.2.0 of the extension
